#!/bin/bash
#
# Gordon prologue, called on the MOM.
#
# See the Torque docs for reference:
# http://docs.adaptivecomputing.com/torque/Content/topics/12-appendices/prologueAndEpliogueScripts.htm

PBS_JOBID=$1
PBS_USER=$2
PBS_GROUP=$3
PBS_JOBNAME=$4
PBS_RESOURCE_LIMITS=$5
JOB_QUEUE=$6
JOB_ACCT=$7

TORQUE_HOME=/var/spool/torque
this_host=$(/bin/hostname -s)

function check_status(){
    # $1 = expected value
    # $2 = status
    # $3 = message if different
    # Offline node if any checks fail and exit

    if [[ $1 != $2 ]] ; then
        note=$3
        /opt/torque/bin/pbsnodes -oN "$note" $this_host
        /usr/bin/logger -p local0.alert "Node offlined due to: $note"
        exit -1
    fi
}

if ( -f /etc/sysconfig/pbs_mom ) then
    . /etc/sysconfig/pbs_mom
endif


# Create local scratch directory
if [[ "$PBS_FLASH" == "noflash" ]]; then
  check_status 0 0 "noflash node"
else
 /bin/mkdir -p /scratch/$PBS_USER/$PBS_JOBID
 check_status 0 $? "Cannot create local scratch"
fi 

# Set local scratch ownership and permissions
/bin/chmod o+rx /scratch/$PBS_USER
/bin/chown -R $PBS_USER /scratch/$PBS_USER/$PBS_JOBID

# Record current /scratch usage
block_usage=$(/bin/df -B 1024 /scratch | /bin/grep scratch)
inode_usage=$(/bin/df -i /scratch | /bin/grep scratch)
/usr/bin/logger -p local0.alert "sdsc_stats job start $PBS_JOBID $PBS_USER local scratch block usage $block_usage"
/usr/bin/logger -p local0.alert "sdsc_stats job start $PBS_JOBID $PBS_USER local scratch inode usage $inode_usage"

# Check for node file to see if we're the mother superior
if [[ -e $TORQUE_HOME/aux/$PBS_JOBID ]] ; then
    # (Mother Superior) Create Oasis scratch dir
    /bin/mkdir -p /oasis/scratch/$PBS_USER/$PBS_JOBID
    check_status 0 $? "Lustre issue, unable to create Oasis scratch dir"

    # Set Oasis scratch ownership and permissions
    /bin/chmod o+rx /oasis/scratch/$PBS_USER
    /bin/chown -R $PBS_USER.$PBS_GROUP /oasis/scratch/$PBS_USER/$PBS_JOBID
fi

if [[ $JOB_QUEUE != "shared" ]] ; then
    # Dedicate use, clean up all job lock files
    /bin/rm -f /tmp/PBS_TEMP_*

    # Set access.conf to default
    /bin/echo '-:ALL EXCEPT root (wheel) (xsede-admin):ALL' > /etc/security/access.conf
fi

# Create user-job lock file
/bin/su - $PBS_USER -c "/bin/touch /tmp/PBS_TEMP_$PBS_JOBID"

# Add user to access list
/bin/sed -i "s/\(EXCEPT.*\):/\1 $PBS_USER:/" /etc/security/access.conf

exit 0
