#!/bin/bash
#
# Gordon prologue, called on the mom. Calls the common script,
# prologue.common.
#
# See the Torque docs for reference:
# http://docs.adaptivecomputing.com/torque/Content/topics/12-appendices/prologueAndEpliogueScripts.htm

PBS_JOBID=$1
PBS_USER=$2
PBS_GROUP=$3
PBS_JOBNAME=$4
PBS_RESOURCE_LIMITS=$5
JOB_QUEUE=$6
JOB_ACCT=$7

TORQUE_HOME=/var/spool/torque
this_host=$(/bin/hostname -s)

function check_status(){
    # $1 = expected value
    # $2 = status
    # $3 = message if different
    # Offline node if any checks fail and exit

    if [[ $1 != $2 ]] ; then
        note=$3
        /opt/torque/bin/pbsnodes -oN "$note" $this_host
        /usr/bin/logger -p local0.alert "Node offlined due to: $note"
        exit -1
    fi
}

# Action 1 - Look for PBS ERROR

/opt/torque/bin/pbsnodes $this_host | grep ERROR  >& /dev/null
check_status 0 $? "ERROR in Torque status"

# Action 3 - Create user-job lock file
/bin/su - $PBS_USER -c "/bin/touch /tmp/PBS_TEMP_$PBS_JOBID"

# Action 5 - Create local scratch directory
/bin/mkdir -p /scratch/$PBS_USER/$PBS_JOBID
check_status 0 $? "Cannot create local scratch"
/bin/chmod o+rx /scratch/$PBS_USER
/bin/chown -R $PBS_USER /scratch/$PBS_USER/$PBS_JOBID

# Check for node file to see if we're the mother superior
if [[ -e /var/spool/torque/aux/$PBS_JOBID ]] ; then
    # Action 5.5 (Mother Superior) - Create Oasis scratch dir
    /bin/mkdir -p /oasis/scratch/$PBS_USER/$PBS_JOBID
    check_status 0 $? "Lustre issue, unable to create Oasis scratch dir"
    /bin/chmod o+rx /oasis/scratch/$PBS_USER
    /bin/chown -R $PBS_USER.$PBS_GROUP /oasis/scratch/$PBS_USER/$PBS_JOBID
else
    # Action 5.5 (Sisters) - Touch stderr/stdout files
    touch $TORQUE_HOME/spool/$PBS_JOBID.OU
    touch $TORQUE_HOME/spool/$PBS_JOBID.ER
fi

# Action 6 - Add user to access list

/bin/sed -i "s/\(EXCEPT.*\):/\1 $PBS_USER:/" access.conf

exit 0
