#!/bin/bash
#
# This script is run out of /etc/rc.d/rocksconfig.d/,
# and is called at boot time. It calls the 
# health-check script, and offlines the node if the
# check fails.
#
# The name is slightly misleading, since not all of the 
# checks are strictly hardware.

# Remove /.rocks-release
if [[ -e /.rocks-release ]] ; then
    /bin/rm /.rocks-release
fi

# Run health check, and offline node if it fails.

note=$(/opt/sdsc/sbin/health-check.sh)
offline=$?

if [[ "$offline" -ne 0 ]] ; then
    this_host=$(/bin/hostname -s)
    /opt/torque/bin/pbsnodes -oN "$note" $this_host
    /usr/bin/logger -p local0.alert "Node offlined due to: $note"
    exit -1
fi

exit 0
